MIN_FISH_PER_TILE = 1
MAX_FISH_PER_TILE = 5

# Dimensions in pixels
TILE_WIDTH = 100
TILE_HEIGHT = 64
TILE_SIDE = 45

AVATAR_WIDTH = 37
AVATAR_HEIGHT = 42

# DELTA = (total_width - straight_edge) / 2 + straight_edge
DELTA = TILE_SIDE + (TILE_WIDTH - TILE_SIDE) / 2
MARGIN_OFFSET = 5

# Adimensional values
DEFAULT_BOARD_ROWS = 4
DEFAULT_BOARD_COLS = 3

ROW_TO_COLUMN_PROBABILITY = 20

SPRITE_PATH = 'sprites'
SPRITE_FORMAT = 'png'

MIN_PLAYERS = 2
MAX_PLAYERS = 4
MIN_PLAYER_AVATAR_NO = 6 - MAX_PLAYERS
MAX_PLAYER_AVATAR_NO = 6 - MIN_PLAYERS
