#!/usr/bin/python3

import argparse
import sys
import unittest

sys.path.append("Other/")

from xtree import xtree
from xtree_tests import xtreeTests


if __name__ == "__main__":
    # Add optional argument to enable unit testing
    parser = argparse.ArgumentParser(description="Run xtree or unit tests")
    parser.add_argument("-u", "--unit", help="Run unit tests", action="store_true")

    args = vars(parser.parse_args())

    # Reset the command line arguments to prevent "unit" argument from being
    # passed to xtree
    sys.argv = ["xtree"]

    # If unit argument was provided, run the unit tests. Otherwise, call xtree
    if args['unit']:
        unittest.main()
    else:
        xtree()
